stages:
  - build
  - test

default:
  image: node:22
  tags:
    - shared-docker-runner

build:
  stage: build
  before_script:
    - apt-get update -qy && apt-get install -y default-jdk
    - npm install -g firebase-tools
  script:
    - echo "Installing dependencies"
    - cd functions && npm install && cd ..
    - echo "Build completed successfully"
  artifacts:
    paths:
      - functions/node_modules/
    expire_in: 1 hour

test:
  stage: test
  dependencies:
    - build
  before_script:
    - apt-get update -qy && apt-get install -y default-jdk
    - npm install -g firebase-tools
  script:
    - firebase emulators:start --project=test-projtect --only firestore,auth &
    - sleep 20
    - export FIRESTORE_EMULATOR_HOST="localhost:8080"
    - export FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
    - cd functions
    - FIRESTORE_EMULATOR_HOST=localhost:8080 FIREBASE_AUTH_EMULATOR_HOST=localhost:9099 node scripts/seed.js seed test-users
    - FIRESTORE_EMULATOR_HOST=localhost:8080 FIREBASE_AUTH_EMULATOR_HOST=localhost:9099 node scripts/seed.js seed global-defense
    - node __tests__/test-runner.js